# 1) JRE builder stage: create a custom slim JRE
FROM eclipse-temurin:21-jdk AS jre-builder
WORKDIR /app

COPY ./build/libs/*-all.jar app.jar

# Extract module dependencies
RUN jdeps \
    --ignore-missing-deps \
    --print-module-deps \
    --multi-release 21 \
    --recursive \
    app.jar > modules.txt

# Create custom JRE
RUN jlink \
    --add-modules $(cat modules.txt),jdk.crypto.ec,jdk.crypto.cryptoki \
    --strip-debug \
    --no-man-pages \
    --no-header-files \
    --compress=2 \
    --output /javaruntime

# 3) Runtime stage: use a slim base and the custom JRE
FROM eclipse-temurin:21-jre AS runtime-base

ENV JAVA_HOME=/opt/java/openjdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"
COPY --from=jre-builder /javaruntime $JAVA_HOME

WORKDIR /app
# Copy the fat jar built by shadowJar from the build stage
COPY ./build/libs/*-all.jar /app.jar

# This is the port that your javalin application will listen on
EXPOSE 7070
ENTRYPOINT ["java", "-jar", "/app.jar"]